/// Single-file exporter: inlines registry sources into one Dart file.
///
/// Pure Dart (no `package:flutter` imports) so web and CLI share it.
/// Callers pass the source map: web passes `kEmbeddedSources` from
/// `../_impl/embedded_sources.dart`, the CLI reads bodies from disk.
import 'screen_doc.dart';

/// Builds a single-file Dart program for [doc], inlining the registry
/// sources of every used component [kind] found in [sourcesByDestination].
///
/// Never throws for unknown kinds: they get a
/// `TODO(canvas): no source for kind` comment plus a placeholder expression.
String buildSingleFile(
  ScreenDoc doc,
  Map<String, String> sourcesByDestination,
) {
  final kinds = _usedKinds(doc);
  final deps = _mergedDeps(kinds);
  final out = StringBuffer()
    ..writeln('// generated by shadcn canvas — DO NOT EDIT.')
    ..writeln(
      '// pubspec: ${deps.isEmpty ? '(none)' : deps.join(', ')}',
    )
    ..writeln(
      '// screens: ${doc.screens.isEmpty ? '(none)' : doc.screens.map((s) => s.name).join(', ')}',
    )
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';");

  for (final screen in doc.screens) {
    out
      ..writeln()
      ..writeln('class ${_classNameFor(screen.name)} extends StatelessWidget {')
      ..writeln('  const ${_classNameFor(screen.name)}({super.key});')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Widget build(BuildContext context) {')
      // Flow root: screen padding outside, vertical Column inside. Gap and
      // padding values come from kFlowScreenGap/kFlowScreenPadding so the
      // generated literals track the model consts.
      ..writeln('    return Padding(')
      ..writeln(
          '      padding: const EdgeInsets.all(${_flowNum(kFlowScreenPadding)}),')
      ..writeln('      child: Column(')
      ..writeln('        crossAxisAlignment: CrossAxisAlignment.start,')
      ..writeln('        children: [');
    final roots = _rootNodes(doc, screen.id);
    if (roots.isEmpty) {
      out.writeln('          // (empty screen)');
    }
    var first = true;
    for (final root in roots) {
      if (!first) {
        out.writeln(
            '          const SizedBox(height: ${_flowNum(kFlowScreenGap)}),');
      }
      first = false;
      _writeFlowChild(out, doc, root, '          ');
    }
    out
      ..writeln('        ],')
      ..writeln('      ),')
      ..writeln('    );')
      ..writeln('  }')
      ..writeln('}');
  }

  for (final kind in kinds) {
    final needle = _kKindPaths[kind] ?? '/$kind/';
    final dests = [
      for (final dest in sourcesByDestination.keys)
        if (dest.contains(needle)) dest,
    ]..sort();
    if (dests.isEmpty) {
      out.writeln();
      out.writeln('// TODO(canvas): no source for kind "$kind"');
      continue;
    }
    for (final dest in dests) {
      out
        ..writeln()
        ..writeln('// from: $dest')
        ..writeln(_stripDirectives(sourcesByDestination[dest]!));
    }
  }
  return out.toString();
}

/// Root flow children for [screenId] in document (insertion) order.
///
/// Nodes whose `parentId` points at a missing node are treated as roots so
/// codegen never silently drops nodes. Row children stay nested under their
/// row via [_writeFlowChild] and are excluded here.
List<CanvasNode> _rootNodes(ScreenDoc doc, String screenId) {
  final ids = {for (final n in doc.nodes) n.id};
  return [
    for (final node in doc.nodes)
      if (node.screenId == screenId &&
          (node.parentId == null || !ids.contains(node.parentId))) node,
  ];
}

/// Writes one root flow child: a leaf's items inline, or a [Row] for a row
/// container whose children are the row's own items plus each child node's
/// items (recurses for nested rows), separated by `SizedBox(width: gap)`.
///
/// No Expanded/Flex/Align v1 (deliberate): rows size to their content and
/// align to the start/center, matching the flow renderer's simple box model.
/// Added only when wrapping or flexible sizing is specified.
void _writeFlowChild(
  StringBuffer out,
  ScreenDoc doc,
  CanvasNode node,
  String indent,
) {
  if (!node.isRow) {
    _writeItemBlock(out, node.items, indent);
    return;
  }
  out
    ..writeln('${indent}Row(')
    ..writeln('$indent  mainAxisAlignment: MainAxisAlignment.start,')
    ..writeln('$indent  crossAxisAlignment: CrossAxisAlignment.center,')
    ..writeln('$indent  children: [');
  final childIndent = '$indent    ';
  var first = true;
  void separator() {
    if (!first) {
      out.writeln(
          '${childIndent}const SizedBox(width: ${_flowNum(node.gap)}),');
    }
    first = false;
  }

  var empty = true;
  if (node.items.isNotEmpty) {
    empty = false;
    separator();
    _writeItemBlock(out, node.items, childIndent);
  }
  for (final child in doc.nodes) {
    if (child.parentId != node.id) continue;
    empty = false;
    separator();
    if (child.isRow) {
      _writeFlowChild(out, doc, child, childIndent);
    } else {
      _writeItemBlock(out, child.items, childIndent);
    }
  }
  if (empty) {
    out.writeln('${childIndent}// (empty row)');
  }
  out
    ..writeln('$indent  ],')
    ..writeln('$indent),');
}

/// Writes item constructor expressions (with tap comments) at [indent].
void _writeItemBlock(
  StringBuffer out,
  List<CanvasItem> items,
  String indent,
) {
  for (final item in items) {
    if (item.action != null) {
      out.writeln('$indent// taps -> ${item.action!.to}');
    }
    for (final line in _itemExpression(item).split('\n')) {
      out.writeln('$indent$line');
    }
  }
}

/// Flow number literal: whole values print without `.0` to match the
/// existing generated style (`EdgeInsets.all(16)`, `SizedBox(height: 12)`).
String _flowNum(double value) =>
    value == value.roundToDouble() ? '${value.toInt()}' : '$value';

/// Used kinds in first-seen order.
List<String> _usedKinds(ScreenDoc doc) {
  final kinds = <String>[];
  for (final node in doc.nodes) {
    for (final item in node.items) {
      if (!kinds.contains(item.kind)) kinds.add(item.kind);
    }
  }
  return kinds;
}

/// Explicit kind → destination-substring table for the catalog kinds.
const Map<String, String> _kKindPaths = {
  'button': '/button/',
  'card': '/card/',
  'input': '/input/',
  'badge': '/badge/',
  'switch': '/switch/',
};

/// Small kind → pubspec deps table (button/card/input need gap+data_widget).
const Map<String, List<String>> _kKindDeps = {
  'button': ['gap', 'data_widget'],
  'card': ['gap', 'data_widget'],
  'input': ['gap', 'data_widget'],
  'badge': <String>[],
  'switch': <String>[],
};

/// Merged deps for [kinds], deduped, first-seen order.
List<String> _mergedDeps(List<String> kinds) {
  final deps = <String>[];
  for (final kind in kinds) {
    for (final dep in _kKindDeps[kind] ?? const <String>[]) {
      if (!deps.contains(dep)) deps.add(dep);
    }
  }
  return deps;
}

/// `Pay` → `CanvasScreen_Pay`; always a valid identifier.
String _classNameFor(String name) {
  final cleaned = name.replaceAll(RegExp(r'[^A-Za-z0-9_]'), '_');
  final safe = cleaned.isEmpty ? 'Screen' : cleaned;
  final prefixed = RegExp(r'^[0-9]').hasMatch(safe) ? 'S_$safe' : safe;
  return 'CanvasScreen_${prefixed[0].toUpperCase()}${prefixed.substring(1)}';
}

/// Dart single-quoted string literal for [value]; never crashes on input.
String _str(Object? value) {
  final escaped = '$value'
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\$', r'\$');
  return "'$escaped'";
}

bool _bool(Map<String, dynamic> props, String key) =>
    props[key] == true;

/// Catalog-equivalent constructor call as text, mirroring
/// `component_catalog.dart` prop→parameter mapping.
String _itemExpression(CanvasItem item) {
  final props = item.props;
  switch (item.kind) {
    case 'button':
      final constructor = switch (props['variant']) {
        'secondary' => 'SecondaryButton',
        'outline' => 'OutlineButton',
        'ghost' => 'GhostButton',
        'destructive' => 'DestructiveButton',
        'link' => 'LinkButton',
        _ => 'PrimaryButton',
      };
      final size = switch (props['size']) {
        'sm' => 'ButtonSize.small',
        'lg' => 'ButtonSize.large',
        _ => 'ButtonSize.normal',
      };
      return '$constructor(\n'
          '  onPressed: () {},\n'
          '  enabled: ${!_bool(props, 'disabled')},\n'
          '  size: $size,\n'
          '  child: Text(${_str(props['label'] ?? 'Button')}),\n'
          '),';
    case 'card':
      final footer = _bool(props, 'showFooter')
          ? '    const SizedBox(height: 12),\n'
              '    PrimaryButton(\n'
              "      size: ButtonSize.small,\n"
              '      onPressed: () {},\n'
              "      child: Text('Action'),\n"
              '    ),\n'
          : '';
      return 'Card(\n'
          '  padding: const EdgeInsets.all(16),\n'
          '  child: Column(\n'
          '    mainAxisSize: MainAxisSize.min,\n'
          '    crossAxisAlignment: CrossAxisAlignment.start,\n'
          '    children: [\n'
          '      Text(${_str(props['title'] ?? 'Card Title')}),\n'
          '      const SizedBox(height: 4),\n'
          '      Text(${_str(props['description'] ?? 'Card description')}),\n'
          '$footer'
          '    ],\n'
          '  ),\n'
          '),';
    case 'input':
      final field = 'TextField(\n'
          '  placeholder: Text(${_str(props['placeholder'] ?? 'Type here')}),\n'
          '  enabled: ${!_bool(props, 'disabled')},\n'
          '  obscureText: ${_bool(props, 'obscure')},\n'
          '),';
      final label = '${props['label'] ?? ''}';
      if (label.isEmpty) return field;
      return 'Column(\n'
          '  mainAxisSize: MainAxisSize.min,\n'
          '  crossAxisAlignment: CrossAxisAlignment.start,\n'
          '  children: [\n'
          '    Text(${_str(label)}),\n'
          '    const SizedBox(height: 6),\n'
          '    $field\n'
          '  ],\n'
          '),';
    case 'badge':
      final constructor = switch (props['variant']) {
        'secondary' => 'SecondaryBadge',
        'destructive' => 'DestructiveBadge',
        'outline' => 'OutlineBadge',
        _ => 'PrimaryBadge',
      };
      return '$constructor(child: Text(${_str(props['label'] ?? 'Badge')})),';
    case 'switch':
      final onChanged =
          _bool(props, 'disabled') ? 'null' : '(v) {}';
      return 'Switch(value: ${_bool(props, 'value')}, onChanged: $onChanged),';
    default:
      return "Text('unknown: ${item.kind}'),";
  }
}

/// Strips `import`/`export`/`part`/`part of`/`library` directives so the
/// body can live in a single file. Directives must precede declarations,
/// so mid-file copies would break validity; relative-URI ones would also
/// dangle. Handles multi-line directives by skipping through `;`.
String _stripDirectives(String body) {
  final kept = <String>[];
  var skipping = false;
  for (final line in body.split('\n')) {
    final trimmed = line.trimLeft();
    if (!skipping &&
        (trimmed.startsWith('import ') ||
            trimmed.startsWith('export ') ||
            trimmed.startsWith('part ') ||
            trimmed.startsWith('library ') ||
            trimmed == 'library;')) {
      if (!line.contains(';')) skipping = true;
      continue;
    }
    if (skipping) {
      if (line.contains(';')) skipping = false;
      continue;
    }
    kept.add(line);
  }
  return kept.join('\n').trimRight();
}
