// Reads components.json canvas blocks for canvas-ready kinds, resolves each
// kind's files[] + shared[] closure (reuse the file/destination lists verbatim),
// and emits a const map: destination -> file content.
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  // Kit root defaults to a `shadcn_flutter_kit` checkout sitting next to this
  // repo (the app itself resolves the kit from GitHub; only regeneration
  // needs a local checkout). Pass it explicitly to override:
  // `dart run tool/embed_sources.dart /path/to/shadcn_flutter_kit`.
  final kitRoot = args.isNotEmpty
      ? args[0]
      : '${File(Platform.script.toFilePath()).parent.parent.parent.path}/shadcn_flutter_kit';
  final manifest = jsonDecode(File(
    '$kitRoot/flutter_shadcn_kit/lib/registry/manifests/components.json',
  ).readAsStringSync()) as Map<String, dynamic>;
  final kitLib = '$kitRoot/flutter_shadcn_kit/lib';
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed_sources.dart — DO NOT EDIT.')
    ..writeln('const Map<String, String> kEmbeddedSources = {');
  for (final c in manifest['components'] as List) {
    if ((c as Map)['canvas'] == null) continue;
    for (final f in (c['files'] as List)) {
      final src = (f as Map)['source'] as String;
      final content = File('$kitLib/$src').readAsStringSync();
      // jsonEncode yields a double-quoted literal, but Dart would still
      // interpolate `$` from embedded sources — escape it (JSON escapes never
      // emit `$`, so every `$` here is a literal content char).
      final encoded = jsonEncode(content).replaceAll(r'$', r'\$');
      out.writeln("  ${jsonEncode(f['destination'])}: $encoded,");
    }
  }
  out.writeln('};');
  // Output always lands in this package's lib/, wherever the kit was read from.
  final appRoot = File(Platform.script.toFilePath()).parent.parent;
  File('${appRoot.path}/lib/canvas/_impl/embedded_sources.dart')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(out.toString());
  stdout.writeln('embedded ${out.length} chars');
}
