// GENERATED by tool/gen_registry.dart — DO NOT EDIT.
// Source: flutter_shadcn_kit lib/registry/manifests/components.json (134 components).
//
// One entry per kit component id plus the `row` pseudo-kind.
// `canvasReady` is true only where a real bare-widget builder
// exists: the 19 catalog kinds bridge to
// `catalog.buildCatalogWithDefaults` (no duplication), the 10
// hand-verified EASY kinds below build real widgets, and the
// `row` pseudo-kind renders its structural Row (rows carry no
// items and lay out in ScreenSurface). Every other kind gets
// [RegistryPlaceholder]: a dashed-border card with the label +
// 'canvas-ready coming soon' — the palette lists them anyway
// (product requirement), rendering honestly.
// Widget names were discovered per kind via
// `grep -rn "^class .* extends .*Widget" <component>/_impl/`,
// never assumed. Preview files are never embedded.
library;

import 'package:flutter/material.dart';

import 'package:canvas_app/canvas/component_catalog.dart' as catalog;
import 'package:canvas_app/shadcn_ui.dart' as shadcn;

/// One palette/canvas registry entry.
///
/// [kind] is the kit component id (or the `row` pseudo-kind).
/// [label] mirrors the manifest description (the palette tile shows
/// the humanized kind; the label is the tooltip + search text).
/// [section] is one of [kRegistrySectionOrder]. [build] constructs
/// the canvas widget with entry defaults (bridged kinds delegate to
/// the catalog, so drop/drop-target behavior is unchanged).
/// [canvasReady] is true only for real bare-widget builders.
class RegistryEntry {
  final String kind;
  final String label;
  final String section;
  final IconData icon;
  final WidgetBuilder build;
  final bool canvasReady;

  const RegistryEntry({
    required this.kind,
    required this.label,
    required this.section,
    required this.icon,
    required this.build,
    required this.canvasReady,
  });
}

/// Palette sections in display order.
const kRegistrySectionOrder = <String>[
  "Layout Primitives",
  "Layout & Structure",
  "Display",
  "Forms & Inputs",
  "Controls",
  "Navigation",
  "Overlays",
  "Utilities",
];

/// Utility ids with no visual canvas footprint. Present in
/// [kRegistry] (coverage) but hidden from the Utilities palette
/// section by [registrySectionEntries].
const kHiddenUtilityKinds = <String>{
  "alpha",
  "async",
  "debug",
  "error_system",
  "locale_utils",
  "shadcn_localizations",
  "shadcn_localizations_en",
  "shadcn_localizations_extensions",
  "wrapper",
};

/// Word-start matcher shared by the palette and its regression
/// tests: every whitespace-separated query token must prefix-match
/// a word start in the entry kind id or label. Substring hits like
/// 'row' in Breadcrumb's 'arrow' separator text no longer match.
bool registryMatchesQuery(RegistryEntry entry, String query) {
  final tokens = query
      .trim()
      .toLowerCase()
      .split(RegExp(r'\s+'))
      .where((t) => t.isNotEmpty)
      .toList();
  if (tokens.isEmpty) return true;
  final words = entry.kind
      .toLowerCase()
      .split(RegExp(r'[^a-z0-9]+'))
      .where((w) => w.isNotEmpty)
      .toList();
  // Tile labels are prettified kind ids ([_tileLabel] in the palette), so
  // matching kind-id words is exactly what the user sees. Descriptions are
  // deliberately NOT matched — 'chips' in a Filter Bar blurb must not make
  // it match 'chip'.
  return tokens.every((t) => words.any((w) => w.startsWith(t)));
}

/// Visible entries for [section] in registry order (hidden
/// utilities excluded — the palette renders sections from this).
List<RegistryEntry> registrySectionEntries(String section) {
  return [
    for (final entry in kRegistry)
      if (entry.section == section &&
          !kHiddenUtilityKinds.contains(entry.kind))
        entry,
  ];
}

/// Looks up a registry entry by kind, or null when unknown.
RegistryEntry? findRegistryEntry(String kind) {
  for (final entry in kRegistry) {
    if (entry.kind == kind) return entry;
  }
  return null;
}

/// Honest placeholder for kinds with no bare-widget builder yet:
/// dashed-border card with the component label plus the
// 'canvas-ready coming soon' note.
class RegistryPlaceholder extends StatelessWidget {
  final String kind;
  final String label;

  const RegistryPlaceholder({
    super.key,
    required this.kind,
    required this.label,
  });

  @override
  Widget build(BuildContext context) {
    final outline = Theme.of(context).colorScheme.outline;
    return CustomPaint(
      painter: _DashPainter(color: outline),
      child: Padding(
        padding: const EdgeInsets.symmetric(
          horizontal: 12,
          vertical: 10,
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(label, textAlign: TextAlign.center),
            const SizedBox(height: 4),
            const Text('canvas-ready coming soon'),
          ],
        ),
      ),
    );
  }
}

/// Dashed rounded-rectangle painter for [RegistryPlaceholder].
class _DashPainter extends CustomPainter {
  final Color color;

  const _DashPainter({required this.color});

  static const _dash = 5.0;
  static const _gap = 3.0;
  static const _radius = 8.0;

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1;
    final rect = Offset.zero & size;
    final path = Path()
      ..addRRect(RRect.fromRectAndRadius(rect, const Radius.circular(_radius)));
    final metrics = path.computeMetrics().single;
    var distance = 0.0;
    while (distance < metrics.length) {
      final end = (distance + _dash).clamp(0.0, metrics.length);
      canvas.drawPath(metrics.extractPath(distance, end), paint);
      distance += _dash + _gap;
    }
  }

  @override
  bool shouldRepaint(covariant _DashPainter oldDelegate) =>
      oldDelegate.color != color;
}
const kAlertEntryDefaults = <String, dynamic>{
  'title': 'Alert',
  'content': 'Something happened.',
  'destructive': false,
};

/// Verified: `Alert` (`layout/alert/alert.dart`) takes optional leading/
/// title/content/trailing widgets plus `destructive` — canvas-level string
/// props render as the title/content Texts.
Widget buildAlertEntry(Map<String, dynamic> props) {
  final title = (props['title'] ?? 'Alert') as String;
  final content = (props['content'] ?? 'Something happened.') as String;
  final destructive = (props['destructive'] ?? false) as bool;
  return shadcn.Alert(
    title: Text(title),
    content: Text(content),
    destructive: destructive,
  );
}

const kChipEntryDefaults = <String, dynamic>{'label': 'Chip'};

/// Verified: `Chip` (`display/chip/chip.dart`) takes a required child plus
/// optional leading/trailing widgets — the canvas-level `label` prop renders
/// as that child (mirrors the badge catalog builder).
Widget buildChipEntry(Map<String, dynamic> props) {
  final label = (props['label'] ?? 'Chip') as String;
  return shadcn.Chip(child: Text(label));
}

const kCircularProgressEntryDefaults = <String, dynamic>{'value': 0.6};

/// Verified: `CircularProgressIndicator`
/// (`display/circular_progress_indicator/`) takes an optional `value`
/// (null = indeterminate). Parsed via `num` because `jsonDecode` yields
/// `int` for whole numbers, and clamped like the progress catalog builder.
Widget buildCircularProgressEntry(Map<String, dynamic> props) {
  final value = ((props['value'] as num?)?.toDouble() ?? 0.6).clamp(0.0, 1.0);
  return shadcn.CircularProgressIndicator(value: value);
}

const kCodeSnippetEntryDefaults = <String, dynamic>{'code': 'const x = 1;'};

/// Verified: `CodeSnippet` (`display/code_snippet/code_snippet.dart`) takes
/// a required `code` Widget plus optional constraints/actions — the
/// canvas-level `code` string prop renders as that child (same content-prop
/// pattern as the card catalog builder; default invented, documented here).
Widget buildCodeSnippetEntry(Map<String, dynamic> props) {
  final code = (props['code'] ?? 'const x = 1;') as String;
  return shadcn.CodeSnippet(code: Text(code));
}

const kDotIndicatorEntryDefaults = <String, dynamic>{'index': 0, 'length': 3};

/// Verified: `DotIndicator` (`display/dot_indicator/dot_indicator.dart`)
/// requires `index` + `length` ints (parsed via `num`, index clamped into
/// range so hand-written docs never crash).
Widget buildDotIndicatorEntry(Map<String, dynamic> props) {
  final length = ((props['length'] as num?)?.toInt() ?? 3).clamp(1, 9);
  final index = ((props['index'] as num?)?.toInt() ?? 0).clamp(0, length - 1);
  return shadcn.DotIndicator(index: index, length: length);
}

const kEmptyStateEntryDefaults = <String, dynamic>{
  'title': 'No results',
  'description': 'Try adjusting your search.',
};

/// Verified: `EmptyState` (`display/empty_state/_impl/core/empty_state.dart`)
/// is all-optional (icon/title/description/actions fall back to per-variant
/// defaults) — canvas-level string props render as the title/description
/// Texts, mirroring the card catalog builder's content-prop pattern.
Widget buildEmptyStateEntry(Map<String, dynamic> props) {
  final title = (props['title'] ?? 'No results') as String;
  final description =
      (props['description'] ?? 'Try adjusting your search.') as String;
  return shadcn.EmptyState(
    title: Text(title),
    description: Text(description),
  );
}

const kLinearProgressEntryDefaults = <String, dynamic>{'value': 0.6};

/// Verified: `LinearProgressIndicator`
/// (`display/linear_progress_indicator/`) takes an optional `value` plus
/// color/minHeight/spark overrides — canvas pins the determinate value
/// (same `num`-parse + clamp idiom as the progress catalog builder).
Widget buildLinearProgressEntry(Map<String, dynamic> props) {
  final value = ((props['value'] as num?)?.toDouble() ?? 0.6).clamp(0.0, 1.0);
  return shadcn.LinearProgressIndicator(value: value);
}

const kNumberTickerEntryDefaults = <String, dynamic>{'value': 42};

/// Verified: `NumberTicker` (`display/number_ticker/number_ticker.dart`)
/// requires `number` + `formatter` (or a builder) — canvas pins a plain
/// integer formatter; the value parses via `num` (default invented,
/// documented here).
Widget buildNumberTickerEntry(Map<String, dynamic> props) {
  final value = (props['value'] as num?)?.toDouble() ?? 42;
  return shadcn.NumberTicker(
    number: value,
    formatter: (v) => v.toStringAsFixed(0),
  );
}

const kTextAreaEntryDefaults = <String, dynamic>{
  'placeholder': 'Type here',
  'label': '',
  'disabled': false,
};

/// Verified: `TextArea` (`form/text_area/text_area.dart`) extends
/// `TextInputStatefulWidget` with all-optional params — mirrors the input
/// catalog builder (`TextField` has no `label` param either, so it renders
/// as a caption above).
Widget buildTextAreaEntry(Map<String, dynamic> props) {
  final placeholder = (props['placeholder'] ?? 'Type here') as String;
  final label = (props['label'] ?? '') as String;
  final disabled = (props['disabled'] ?? false) as bool;
  final field = shadcn.TextArea(
    placeholder: Text(placeholder),
    enabled: !disabled,
  );
  if (label.isEmpty) return field;
  return Column(
    mainAxisSize: MainAxisSize.min,
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text(label),
      const SizedBox(height: 6),
      field,
    ],
  );
}

const kTripleDotsEntryDefaults = <String, dynamic>{'count': 3};

/// Verified: `MoreDots` (`display/triple_dots/triple_dots.dart`) takes
/// direction/count/size/color/spacing/padding, all defaulted — the
/// canvas-level `count` prop is an int (parsed via `num`, clamped to a
/// sane range).
Widget buildTripleDotsEntry(Map<String, dynamic> props) {
  final count = ((props['count'] as num?)?.toInt() ?? 3).clamp(1, 9);
  return shadcn.MoreDots(count: count);
}

/// Full registry: every kit component id plus the `row`
/// pseudo-kind, grouped by [kRegistrySectionOrder] (kinds
/// alphabetical within a section).
final List<RegistryEntry> kRegistry = [
  // Layout Primitives.
  RegistryEntry(
    kind: 'row',
    label: 'Row',
    section: 'Layout Primitives',
    icon: Icons.view_column,
    // Rows carry no items and lay out structurally in
    // ScreenSurface (see kContainerTiles); this builder renders
    // the same horizontal structure for standalone previews.
    build: (_) => const Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(Icons.view_column, size: 20),
        SizedBox(width: 8),
        Text('Row'),
      ],
    ),
    canvasReady: true,
  ),
  // Layout & Structure.
  RegistryEntry(
    kind: "accordion",
    label: "Single-expansion accordion with configurable triggers and theming.",
    section: "Layout & Structure",
    icon: Icons.expand_more,
    build: (context) => catalog.buildCatalogWithDefaults("accordion"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "alert",
    label: "Flexible alert panels with destructive/resilient styling.",
    section: "Layout & Structure",
    icon: Icons.warning_amber,
    build: (context) => buildAlertEntry(kAlertEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "app",
    label: "App wrapper with shadcn theme and overlay handling.",
    section: "Layout & Structure",
    icon: Icons.apps,
    build: (context) => RegistryPlaceholder(kind: "app", label: "App wrapper with shadcn theme and overlay handling."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "basic",
    label: "Flexible row layout for leading/title/content/trailing sections.",
    section: "Layout & Structure",
    icon: Icons.view_agenda,
    build: (context) => RegistryPlaceholder(kind: "basic", label: "Flexible row layout for leading/title/content/trailing sections."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "card",
    label: "Card container with optional surface blur variant.",
    section: "Layout & Structure",
    icon: Icons.crop_square,
    build: (context) => catalog.buildCatalogWithDefaults("card"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "card_image",
    label: "Interactive card that pairs an image with title/subtitle content.",
    section: "Layout & Structure",
    icon: Icons.image,
    build: (context) => RegistryPlaceholder(kind: "card_image", label: "Interactive card that pairs an image with title/subtitle content."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "collapsible",
    label: "Independent sections that toggle their own visibility",
    section: "Layout & Structure",
    icon: Icons.unfold_more,
    build: (context) => RegistryPlaceholder(kind: "collapsible", label: "Independent sections that toggle their own visibility"),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "fade_scroll",
    label: "Edge fade overlays for scrollable content.",
    section: "Layout & Structure",
    icon: Icons.unfold_less,
    build: (context) => RegistryPlaceholder(kind: "fade_scroll", label: "Edge fade overlays for scrollable content."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "filter_bar",
    label: "Controlled filter toolbar for list/table pages with search, sort, chips, date range, and clear-all.",
    section: "Layout & Structure",
    icon: Icons.filter_list,
    build: (context) => RegistryPlaceholder(kind: "filter_bar", label: "Controlled filter toolbar for list/table pages with search, sort, chips, date range, and clear-all."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "flex",
    label: "Flex component for the registry.",
    section: "Layout & Structure",
    icon: Icons.view_stream,
    build: (context) => RegistryPlaceholder(kind: "flex", label: "Flex component for the registry."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "group",
    label: "Absolute-position layout surface with explicit offsets and sizes.",
    section: "Layout & Structure",
    icon: Icons.group,
    build: (context) => RegistryPlaceholder(kind: "group", label: "Absolute-position layout surface with explicit offsets and sizes."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "hidden",
    label: "Animated visibility helper with axis-aware size control.",
    section: "Layout & Structure",
    icon: Icons.visibility_off,
    build: (context) => RegistryPlaceholder(kind: "hidden", label: "Animated visibility helper with axis-aware size control."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "media_query",
    label: "Responsive helper that shows primary or alternate content based on width constraints.",
    section: "Layout & Structure",
    icon: Icons.devices,
    build: (context) => RegistryPlaceholder(kind: "media_query", label: "Responsive helper that shows primary or alternate content based on width constraints."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "outlined_container",
    label: "Animated outlined container with theme-aware borders and blur.",
    section: "Layout & Structure",
    icon: Icons.check_box_outline_blank,
    build: (context) => RegistryPlaceholder(kind: "outlined_container", label: "Animated outlined container with theme-aware borders and blur."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "overflow_marquee",
    label: "Smooth marquee for overflowing content with fade edges and looped timing controls.",
    section: "Layout & Structure",
    icon: Icons.wrap_text,
    build: (context) => RegistryPlaceholder(kind: "overflow_marquee", label: "Smooth marquee for overflowing content with fade edges and looped timing controls."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "resizable",
    label: "Resizable panels with draggable dividers.",
    section: "Layout & Structure",
    icon: Icons.open_in_full,
    build: (context) => RegistryPlaceholder(kind: "resizable", label: "Resizable panels with draggable dividers."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "scaffold",
    label: "Layout scaffold with headers, footers, and loading indicators.",
    section: "Layout & Structure",
    icon: Icons.view_quilt,
    build: (context) => RegistryPlaceholder(kind: "scaffold", label: "Layout scaffold with headers, footers, and loading indicators."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "scrollable",
    label: "Two-dimensional scrollable client and faded viewport utilities.",
    section: "Layout & Structure",
    icon: Icons.import_export,
    build: (context) => RegistryPlaceholder(kind: "scrollable", label: "Two-dimensional scrollable client and faded viewport utilities."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "scrollable_client",
    label: "Two-dimensional scroll surface with builder callbacks for viewport-aware layouts.",
    section: "Layout & Structure",
    icon: Icons.zoom_out_map,
    build: (context) => RegistryPlaceholder(kind: "scrollable_client", label: "Two-dimensional scroll surface with builder callbacks for viewport-aware layouts."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "sortable",
    label: "Drag-and-drop sorting primitives with drop zones and scrolling.",
    section: "Layout & Structure",
    icon: Icons.sort,
    build: (context) => RegistryPlaceholder(kind: "sortable", label: "Drag-and-drop sorting primitives with drop zones and scrolling."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "stage_container",
    label: "Responsive container that snaps to breakpoint widths.",
    section: "Layout & Structure",
    icon: Icons.desktop_windows,
    build: (context) => RegistryPlaceholder(kind: "stage_container", label: "Responsive container that snaps to breakpoint widths."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "steps",
    label: "Vertical step list with numbered indicators and connectors.",
    section: "Layout & Structure",
    icon: Icons.format_list_numbered,
    build: (context) => RegistryPlaceholder(kind: "steps", label: "Vertical step list with numbered indicators and connectors."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "table",
    label: "Resizable table layout with headers, footers, and frozen cells.",
    section: "Layout & Structure",
    icon: Icons.table_chart,
    build: (context) => RegistryPlaceholder(kind: "table", label: "Resizable table layout with headers, footers, and frozen cells."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "timeline",
    label: "Vertical timeline for chronological entries.",
    section: "Layout & Structure",
    icon: Icons.timeline,
    build: (context) => RegistryPlaceholder(kind: "timeline", label: "Vertical timeline for chronological entries."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "window",
    label: "Desktop-style window system with drag, resize, and snapping.",
    section: "Layout & Structure",
    icon: Icons.web,
    build: (context) => RegistryPlaceholder(kind: "window", label: "Desktop-style window system with drag, resize, and snapping."),
    canvasReady: false,
  ),
  // Display.
  RegistryEntry(
    kind: "avatar",
    label: "Initials/photo avatar with badge and group support.",
    section: "Display",
    icon: Icons.account_circle,
    build: (context) => catalog.buildCatalogWithDefaults("avatar"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "badge",
    label: "Compact label/status components built on button styles.",
    section: "Display",
    icon: Icons.label,
    build: (context) => catalog.buildCatalogWithDefaults("badge"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "border_loading",
    label: "Animated border loader wrapper (sweep/linear/radial gradients + tracer mode + circle/custom shapes).",
    section: "Display",
    icon: Icons.blur_circular,
    build: (context) => RegistryPlaceholder(kind: "border_loading", label: "Animated border loader wrapper (sweep/linear/radial gradients + tracer mode + circle/custom shapes)."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "calendar",
    label: "Date picker and calendar widgets for single, range, and multi selection.",
    section: "Display",
    icon: Icons.calendar_month,
    build: (context) => RegistryPlaceholder(kind: "calendar", label: "Date picker and calendar widgets for single, range, and multi selection."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "carousel",
    label: "Interactive carousel with sliding/fading transitions and autoplay controls.",
    section: "Display",
    icon: Icons.slideshow,
    build: (context) => RegistryPlaceholder(kind: "carousel", label: "Interactive carousel with sliding/fading transitions and autoplay controls."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "chat",
    label: "Chat bubbles, groups, and tail helpers for conversational layouts.",
    section: "Display",
    icon: Icons.chat_bubble_outline,
    build: (context) => RegistryPlaceholder(kind: "chat", label: "Chat bubbles, groups, and tail helpers for conversational layouts."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "chip",
    label: "Compact tag-style button with optional leading/trailing widgets.",
    section: "Display",
    icon: Icons.local_offer,
    build: (context) => buildChipEntry(kChipEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "circular_progress_indicator",
    label: "Determinate/indeterminate spinner with theme overrides and optional animation.",
    section: "Display",
    icon: Icons.autorenew,
    build: (context) => buildCircularProgressEntry(kCircularProgressEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "code_snippet",
    label: "Stylized code container with action slot and theme overrides.",
    section: "Display",
    icon: Icons.code,
    build: (context) => buildCodeSnippetEntry(kCodeSnippetEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "divider",
    label: "Horizontal and vertical separators with optional label support.",
    section: "Display",
    icon: Icons.horizontal_rule,
    build: (context) => catalog.buildCatalogWithDefaults("divider"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "dot_indicator",
    label: "Animated dot indicator for carousels/steppers with optional tap behavior.",
    section: "Display",
    icon: Icons.fiber_manual_record,
    build: (context) => buildDotIndicatorEntry(kDotIndicatorEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "empty_state",
    label: "Standardized empty state block for empty, no-results, or error.",
    section: "Display",
    icon: Icons.inbox,
    build: (context) => buildEmptyStateEntry(kEmptyStateEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "feature_carousel",
    label: "Animated feature card carousel with autoplay, swipe, and CTA support. (WIP)",
    section: "Display",
    icon: Icons.view_carousel,
    build: (context) => RegistryPlaceholder(kind: "feature_carousel", label: "Animated feature card carousel with autoplay, swipe, and CTA support. (WIP)"),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "file_diff_viewer",
    label: "A comprehensive file diff viewer with unified and split layouts.",
    section: "Display",
    icon: Icons.compare,
    build: (context) => RegistryPlaceholder(kind: "file_diff_viewer", label: "A comprehensive file diff viewer with unified and split layouts."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "icon",
    label: "Theme-driven icon size/color helpers and WrappedIcon.",
    section: "Display",
    icon: Icons.insert_emoticon,
    build: (context) => RegistryPlaceholder(kind: "icon", label: "Theme-driven icon size/color helpers and WrappedIcon."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "keyboard_shortcut",
    label: "Displays keyboard shortcuts as styled keycaps.",
    section: "Display",
    icon: Icons.keyboard,
    build: (context) => RegistryPlaceholder(kind: "keyboard_shortcut", label: "Displays keyboard shortcuts as styled keycaps."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "linear_progress_indicator",
    label: "Determinate/indeterminate progress bar with optional spark effects and theming.",
    section: "Display",
    icon: Icons.bar_chart,
    build: (context) => buildLinearProgressEntry(kLinearProgressEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "markdown",
    label: "Advanced markdown renderer with asset/file sources and optional streaming support.",
    section: "Display",
    icon: Icons.article,
    build: (context) => RegistryPlaceholder(kind: "markdown", label: "Advanced markdown renderer with asset/file sources and optional streaming support."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "number_ticker",
    label: "Animated number display with formatter or custom builder.",
    section: "Display",
    icon: Icons.timer,
    build: (context) => buildNumberTickerEntry(kNumberTickerEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "progress",
    label: "Normalized linear progress bar with theme overrides.",
    section: "Display",
    icon: Icons.linear_scale,
    build: (context) => catalog.buildCatalogWithDefaults("progress"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "selectable",
    label: "Selectable text with themed cursor and selection behavior.",
    section: "Display",
    icon: Icons.select_all,
    build: (context) => RegistryPlaceholder(kind: "selectable", label: "Selectable text with themed cursor and selection behavior."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "skeleton",
    label: "Skeletonizer helpers with theme-aware config and extensions.",
    section: "Display",
    icon: Icons.blur_on,
    build: (context) => catalog.buildCatalogWithDefaults("skeleton"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "spinner",
    label: "Base spinner helpers for resolving color and size with theming.",
    section: "Display",
    icon: Icons.refresh,
    build: (context) => RegistryPlaceholder(kind: "spinner", label: "Base spinner helpers for resolving color and size with theming."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "text",
    label: "Typography helpers and fluent text modifiers.",
    section: "Display",
    icon: Icons.text_format,
    build: (context) => RegistryPlaceholder(kind: "text", label: "Typography helpers and fluent text modifiers."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "text_animate",
    label: "Stream-aware animated text renderer for incremental updates.",
    section: "Display",
    icon: Icons.animation,
    build: (context) => RegistryPlaceholder(kind: "text_animate", label: "Stream-aware animated text renderer for incremental updates."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "tracker",
    label: "Horizontal tracker segments with tooltips.",
    section: "Display",
    icon: Icons.track_changes,
    build: (context) => RegistryPlaceholder(kind: "tracker", label: "Horizontal tracker segments with tooltips."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "tree",
    label: "Hierarchical tree view with expandable, selectable nodes.",
    section: "Display",
    icon: Icons.account_tree,
    build: (context) => RegistryPlaceholder(kind: "tree", label: "Hierarchical tree view with expandable, selectable nodes."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "triple_dots",
    label: "Configurable row/column of dots for menu or loading indicators.",
    section: "Display",
    icon: Icons.more_horiz,
    build: (context) => buildTripleDotsEntry(kTripleDotsEntryDefaults),
    canvasReady: true,
  ),
  // Forms & Inputs.
  RegistryEntry(
    kind: "autocomplete",
    label: "Autocomplete overlay for text inputs with keyboard navigation and theming.",
    section: "Forms & Inputs",
    icon: Icons.auto_awesome,
    build: (context) => RegistryPlaceholder(kind: "autocomplete", label: "Autocomplete overlay for text inputs with keyboard navigation and theming."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "checkbox",
    label: "Animated checkbox with tri-state support and controllers.",
    section: "Forms & Inputs",
    icon: Icons.check_box,
    build: (context) => catalog.buildCatalogWithDefaults("checkbox"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "chip_input",
    label: "Inline text input that converts typed tokens into chip widgets with removable buttons and autocomplete hooks.",
    section: "Forms & Inputs",
    icon: Icons.new_label,
    build: (context) => RegistryPlaceholder(kind: "chip_input", label: "Inline text input that converts typed tokens into chip widgets with removable buttons and autocomplete hooks."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "color_input",
    label: "Popover/dialog color selector that integrates the picker, history, and eye-dropper tools.",
    section: "Forms & Inputs",
    icon: Icons.colorize,
    build: (context) => RegistryPlaceholder(kind: "color_input", label: "Popover/dialog color selector that integrates the picker, history, and eye-dropper tools."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "color_picker",
    label: "HSV/HSL/HEX color picker with popovers, eye dropper, and history controls.",
    section: "Forms & Inputs",
    icon: Icons.palette,
    build: (context) => RegistryPlaceholder(kind: "color_picker", label: "HSV/HSL/HEX color picker with popovers, eye dropper, and history controls."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "control",
    label: "Controller mixins and helpers for form components.",
    section: "Forms & Inputs",
    icon: Icons.handyman,
    build: (context) => RegistryPlaceholder(kind: "control", label: "Controller mixins and helpers for form components."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "date_picker",
    label: "Popover/dialog calendar for single-date and range selection.",
    section: "Forms & Inputs",
    icon: Icons.date_range,
    build: (context) => RegistryPlaceholder(kind: "date_picker", label: "Popover/dialog calendar for single-date and range selection."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "dropzone",
    label: "Dropzone surface for file uploads.",
    section: "Forms & Inputs",
    icon: Icons.upload_file,
    build: (context) => RegistryPlaceholder(kind: "dropzone", label: "Dropzone surface for file uploads."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "file_input",
    label: "Utilities for mapping file extensions to icon widgets.",
    section: "Forms & Inputs",
    icon: Icons.attach_file,
    build: (context) => RegistryPlaceholder(kind: "file_input", label: "Utilities for mapping file extensions to icon widgets."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "file_picker",
    label: "UI-only drag-drop, tile, and mobile file picker surfaces with upload list management.",
    section: "Forms & Inputs",
    icon: Icons.folder_open,
    build: (context) => RegistryPlaceholder(kind: "file_picker", label: "UI-only drag-drop, tile, and mobile file picker surfaces with upload list management."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "form",
    label: "Composable form state, validation, and submit helpers.",
    section: "Forms & Inputs",
    icon: Icons.assignment,
    build: (context) => RegistryPlaceholder(kind: "form", label: "Composable form state, validation, and submit helpers."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "form_field",
    label: "Modal or popover editor field for complex objects.",
    section: "Forms & Inputs",
    icon: Icons.edit_note,
    build: (context) => RegistryPlaceholder(kind: "form_field", label: "Modal or popover editor field for complex objects."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "formatted_input",
    label: "Low-level formatted-field helpers that sync multiple InputPart segments.",
    section: "Forms & Inputs",
    icon: Icons.text_snippet,
    build: (context) => RegistryPlaceholder(kind: "formatted_input", label: "Low-level formatted-field helpers that sync multiple InputPart segments."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "formatter",
    label: "Reusable text input formatters (uppercase/lowercase, numeric, math, HEX, etc.) and helpers for selection clipping.",
    section: "Forms & Inputs",
    icon: Icons.format_bold,
    build: (context) => RegistryPlaceholder(kind: "formatter", label: "Reusable text input formatters (uppercase/lowercase, numeric, math, HEX, etc.) and helpers for selection clipping."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "history",
    label: "Grid + storage helpers that track recently used colors for reuse.",
    section: "Forms & Inputs",
    icon: Icons.history,
    build: (context) => RegistryPlaceholder(kind: "history", label: "Grid + storage helpers that track recently used colors for reuse."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "hsl",
    label: "Gradient slider that controls hue, saturation, lightness, or alpha for HSL colors.",
    section: "Forms & Inputs",
    icon: Icons.gradient,
    build: (context) => RegistryPlaceholder(kind: "hsl", label: "Gradient slider that controls hue, saturation, lightness, or alpha for HSL colors."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "hsv",
    label: "Gradient slider for HSV color component control (hue, saturation, value, alpha).",
    section: "Forms & Inputs",
    icon: Icons.color_lens,
    build: (context) => RegistryPlaceholder(kind: "hsv", label: "Gradient slider for HSV color component control (hue, saturation, value, alpha)."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "input",
    label: "Single-line text input with feature hooks, popovers, and controller integration.",
    section: "Forms & Inputs",
    icon: Icons.text_fields,
    build: (context) => catalog.buildCatalogWithDefaults("input"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "input_otp",
    label: "Fixed-length OTP input field with clipboard integration, paste handling, and focus management.",
    section: "Forms & Inputs",
    icon: Icons.dialpad,
    build: (context) => RegistryPlaceholder(kind: "input_otp", label: "Fixed-length OTP input field with clipboard integration, paste handling, and focus management."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "item_picker",
    label: "Grid/list picker with selection chips, search, and in-place actions.",
    section: "Forms & Inputs",
    icon: Icons.checklist,
    build: (context) => RegistryPlaceholder(kind: "item_picker", label: "Grid/list picker with selection chips, search, and in-place actions."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "multiple_choice",
    label: "Choice widgets with single or multiple selection and form integration.",
    section: "Forms & Inputs",
    icon: Icons.ballot,
    build: (context) => RegistryPlaceholder(kind: "multiple_choice", label: "Choice widgets with single or multiple selection and form integration."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "object_input",
    label: "Date, time, and duration inputs powered by formatted editors and pickers.",
    section: "Forms & Inputs",
    icon: Icons.event,
    build: (context) => RegistryPlaceholder(kind: "object_input", label: "Date, time, and duration inputs powered by formatted editors and pickers."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "phone_input",
    label: "International phone number input with country selector and formatting helpers.",
    section: "Forms & Inputs",
    icon: Icons.phone,
    build: (context) => RegistryPlaceholder(kind: "phone_input", label: "International phone number input with country selector and formatting helpers."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "radio_group",
    label: "Exclusive selection group with radio items and cards.",
    section: "Forms & Inputs",
    icon: Icons.radio_button_checked,
    build: (context) => catalog.buildCatalogWithDefaults("radio_group"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "select",
    label: "Dropdown/select control with popup menus, grouped items, and keyboard navigation.",
    section: "Forms & Inputs",
    icon: Icons.arrow_drop_down_circle,
    build: (context) => catalog.buildCatalogWithDefaults("select"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "slider",
    label: "General-purpose single and range slider engine with snapping and pluggable builders.",
    section: "Forms & Inputs",
    icon: Icons.tune,
    build: (context) => RegistryPlaceholder(kind: "slider", label: "General-purpose single and range slider engine with snapping and pluggable builders."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "star_rating",
    label: "Interactive star rating input with theming support.",
    section: "Forms & Inputs",
    icon: Icons.star,
    build: (context) => RegistryPlaceholder(kind: "star_rating", label: "Interactive star rating input with theming support."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "switch",
    label: "Toggle control for boolean values with themed styling.",
    section: "Forms & Inputs",
    icon: Icons.toggle_on,
    build: (context) => catalog.buildCatalogWithDefaults("switch"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "text_area",
    label: "Resizable multi-line text input built on text field primitives.",
    section: "Forms & Inputs",
    icon: Icons.subject,
    build: (context) => buildTextAreaEntry(kTextAreaEntryDefaults),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "text_field",
    label: "Text input with rich features, autocomplete, and actions.",
    section: "Forms & Inputs",
    icon: Icons.short_text,
    build: (context) => RegistryPlaceholder(kind: "text_field", label: "Text input with rich features, autocomplete, and actions."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "time_picker",
    label: "Popover/dialog picker for time and duration values.",
    section: "Forms & Inputs",
    icon: Icons.schedule,
    build: (context) => RegistryPlaceholder(kind: "time_picker", label: "Popover/dialog picker for time and duration values."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "validated",
    label: "Validation wrapper that exposes form error state.",
    section: "Forms & Inputs",
    icon: Icons.verified,
    build: (context) => RegistryPlaceholder(kind: "validated", label: "Validation wrapper that exposes form error state."),
    canvasReady: false,
  ),
  // Controls.
  RegistryEntry(
    kind: "button",
    label: "Shadcn-style button system with variants, toggles, and groups.",
    section: "Controls",
    icon: Icons.smart_button,
    build: (context) => catalog.buildCatalogWithDefaults("button"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "clickable",
    label: "State-aware gesture surface with hover, focus, and press handling.",
    section: "Controls",
    icon: Icons.touch_app,
    build: (context) => RegistryPlaceholder(kind: "clickable", label: "State-aware gesture surface with hover, focus, and press handling."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "command",
    label: "Command palette with search, keyboard navigation, and customizable result builders.",
    section: "Controls",
    icon: Icons.terminal,
    build: (context) => RegistryPlaceholder(kind: "command", label: "Command palette with search, keyboard navigation, and customizable result builders."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "hover",
    label: "Hover timing helpers plus lightweight state tracking widgets.",
    section: "Controls",
    icon: Icons.mouse,
    build: (context) => RegistryPlaceholder(kind: "hover", label: "Hover timing helpers plus lightweight state tracking widgets."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "patch",
    label: "Tracks consecutive taps and exposes click count details.",
    section: "Controls",
    icon: Icons.fingerprint,
    build: (context) => RegistryPlaceholder(kind: "patch", label: "Tracks consecutive taps and exposes click count details."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "scrollbar",
    label: "Themeable scrollbar wrapper built on RawScrollbar.",
    section: "Controls",
    icon: Icons.swap_vert,
    build: (context) => RegistryPlaceholder(kind: "scrollbar", label: "Themeable scrollbar wrapper built on RawScrollbar."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "scrollview",
    label: "Middle-click drag scroll interceptor for desktop/web.",
    section: "Controls",
    icon: Icons.swipe,
    build: (context) => RegistryPlaceholder(kind: "scrollview", label: "Middle-click drag scroll interceptor for desktop/web."),
    canvasReady: false,
  ),
  // Navigation.
  RegistryEntry(
    kind: "breadcrumb",
    label: "Horizontal breadcrumb trail with arrow/slash separators and overflow handling.",
    section: "Navigation",
    icon: Icons.chevron_right,
    build: (context) => catalog.buildCatalogWithDefaults("breadcrumb"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "navigation_bar",
    label: "Themed navigation bar supporting destinations, overflow, and responsive layout.",
    section: "Navigation",
    icon: Icons.navigation,
    build: (context) => RegistryPlaceholder(kind: "navigation_bar", label: "Themed navigation bar supporting destinations, overflow, and responsive layout."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "navigation_menu",
    label: "Dropdown-style navigation menu with popovers, groups, and keyboard navigation.",
    section: "Navigation",
    icon: Icons.menu,
    build: (context) => RegistryPlaceholder(kind: "navigation_menu", label: "Dropdown-style navigation menu with popovers, groups, and keyboard navigation."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "pagination",
    label: "Page navigation controls with skip, previous/next, and ellipsis handling.",
    section: "Navigation",
    icon: Icons.last_page,
    build: (context) => RegistryPlaceholder(kind: "pagination", label: "Page navigation controls with skip, previous/next, and ellipsis handling."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "stepper",
    label: "Multi-step progress with interactive step indicators.",
    section: "Navigation",
    icon: Icons.directions_walk,
    build: (context) => RegistryPlaceholder(kind: "stepper", label: "Multi-step progress with interactive step indicators."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "subfocus",
    label: "Hierarchical focus scope for keyboard navigation.",
    section: "Navigation",
    icon: Icons.center_focus_strong,
    build: (context) => RegistryPlaceholder(kind: "subfocus", label: "Hierarchical focus scope for keyboard navigation."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "switcher",
    label: "Swipeable viewport that animates between children along an axis.",
    section: "Navigation",
    icon: Icons.tab_unselected,
    build: (context) => RegistryPlaceholder(kind: "switcher", label: "Swipeable viewport that animates between children along an axis."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "tab_container",
    label: "Coordinated tab state manager with customizable builders.",
    section: "Navigation",
    icon: Icons.view_module,
    build: (context) => RegistryPlaceholder(kind: "tab_container", label: "Coordinated tab state manager with customizable builders."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "tab_list",
    label: "Horizontal tab header row with active indicator.",
    section: "Navigation",
    icon: Icons.view_list,
    build: (context) => RegistryPlaceholder(kind: "tab_list", label: "Horizontal tab header row with active indicator."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "tab_pane",
    label: "Sortable tab strip with integrated content card.",
    section: "Navigation",
    icon: Icons.dock,
    build: (context) => RegistryPlaceholder(kind: "tab_pane", label: "Sortable tab strip with integrated content card."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "tabs",
    label: "Tabbed navigation primitives with lists and panes.",
    section: "Navigation",
    icon: Icons.tab,
    build: (context) => catalog.buildCatalogWithDefaults("tabs"),
    canvasReady: true,
  ),
  // Overlays.
  RegistryEntry(
    kind: "alert_dialog",
    label: "Modal alert dialog with customizable header, content, and actions.",
    section: "Overlays",
    icon: Icons.error_outline,
    build: (context) => RegistryPlaceholder(kind: "alert_dialog", label: "Modal alert dialog with customizable header, content, and actions."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "context_menu",
    label: "Desktop-style context menu overlay for editable text and custom actions.",
    section: "Overlays",
    icon: Icons.more_vert,
    build: (context) => RegistryPlaceholder(kind: "context_menu", label: "Desktop-style context menu overlay for editable text and custom actions."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "dialog",
    label: "Modal dialog primitives with alert dialog and overlay handlers.",
    section: "Overlays",
    icon: Icons.web_asset,
    build: (context) => catalog.buildCatalogWithDefaults("dialog"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "drawer",
    label: "Sliding drawer and sheet overlays with drag support.",
    section: "Overlays",
    icon: Icons.menu_open,
    build: (context) => catalog.buildCatalogWithDefaults("drawer"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "dropdown_menu",
    label: "Dropdown menu overlay built on menu primitives.",
    section: "Overlays",
    icon: Icons.arrow_drop_down,
    build: (context) => RegistryPlaceholder(kind: "dropdown_menu", label: "Dropdown menu overlay built on menu primitives."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "eye_dropper",
    label: "Layer that lets users sample colors from the screen with preview adornments.",
    section: "Overlays",
    icon: Icons.brush,
    build: (context) => RegistryPlaceholder(kind: "eye_dropper", label: "Layer that lets users sample colors from the screen with preview adornments."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "gooey_toast",
    label: "Animated gooey-style toast built on existing overlay toast infrastructure.",
    section: "Overlays",
    icon: Icons.notification_add,
    build: (context) => RegistryPlaceholder(kind: "gooey_toast", label: "Animated gooey-style toast built on existing overlay toast infrastructure."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "hover_card",
    label: "Hover or long-press triggered popovers for rich previews.",
    section: "Overlays",
    icon: Icons.preview,
    build: (context) => RegistryPlaceholder(kind: "hover_card", label: "Hover or long-press triggered popovers for rich previews."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "menu",
    label: "Menu primitives, items, and popup container.",
    section: "Overlays",
    icon: Icons.list,
    build: (context) => RegistryPlaceholder(kind: "menu", label: "Menu primitives, items, and popup container."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "menubar",
    label: "Horizontal desktop-style menubar with dropdown menus and keyboard navigation.",
    section: "Overlays",
    icon: Icons.view_headline,
    build: (context) => RegistryPlaceholder(kind: "menubar", label: "Horizontal desktop-style menubar with dropdown menus and keyboard navigation."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "overlay",
    label: "Shared overlay handler/manager utilities and helpers.",
    section: "Overlays",
    icon: Icons.layers,
    build: (context) => RegistryPlaceholder(kind: "overlay", label: "Shared overlay handler/manager utilities and helpers."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "popover",
    label: "Anchored overlay surfaces for floating content.",
    section: "Overlays",
    icon: Icons.chat_bubble,
    build: (context) => RegistryPlaceholder(kind: "popover", label: "Anchored overlay surfaces for floating content."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "popup",
    label: "Styled popup container for menus and dropdowns.",
    section: "Overlays",
    icon: Icons.launch,
    build: (context) => RegistryPlaceholder(kind: "popup", label: "Styled popup container for menus and dropdowns."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "refresh_trigger",
    label: "Pull-to-refresh wrapper with customizable indicator, extents, and completion animations.",
    section: "Overlays",
    icon: Icons.refresh,
    build: (context) => RegistryPlaceholder(kind: "refresh_trigger", label: "Pull-to-refresh wrapper with customizable indicator, extents, and completion animations."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "swiper",
    label: "Swipe-triggered overlays for drawers and sheets.",
    section: "Overlays",
    icon: Icons.gesture,
    build: (context) => RegistryPlaceholder(kind: "swiper", label: "Swipe-triggered overlays for drawers and sheets."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "toast",
    label: "Overlay toast notifications with configurable timing.",
    section: "Overlays",
    icon: Icons.notifications,
    build: (context) => catalog.buildCatalogWithDefaults("toast"),
    canvasReady: true,
  ),
  RegistryEntry(
    kind: "tooltip",
    label: "Hover-triggered tooltip overlays with themed containers.",
    section: "Overlays",
    icon: Icons.help_outline,
    build: (context) => catalog.buildCatalogWithDefaults("tooltip"),
    canvasReady: true,
  ),
  // Utilities.
  RegistryEntry(
    kind: "alpha",
    label: "Checkerboard painter for transparency indicators.",
    section: "Utilities",
    icon: Icons.grid_on,
    build: (context) => RegistryPlaceholder(kind: "alpha", label: "Checkerboard painter for transparency indicators."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "async",
    label: "Utility for widgets that work with both synchronous and asynchronous values.",
    section: "Utilities",
    icon: Icons.sync,
    build: (context) => RegistryPlaceholder(kind: "async", label: "Utility for widgets that work with both synchronous and asynchronous values."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "color",
    label: "Helper utilities for converting and transforming colors across RGB/HSV/HSL spaces.",
    section: "Utilities",
    icon: Icons.format_color_fill,
    build: (context) => RegistryPlaceholder(kind: "color", label: "Helper utilities for converting and transforming colors across RGB/HSV/HSL spaces."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "debug",
    label: "Debug overlays and container helpers for layout inspection.",
    section: "Utilities",
    icon: Icons.bug_report,
    build: (context) => RegistryPlaceholder(kind: "debug", label: "Debug overlays and container helpers for layout inspection."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "error_system",
    label: "Production-ready error handling system with UI components and repository mapping.",
    section: "Utilities",
    icon: Icons.error,
    build: (context) => RegistryPlaceholder(kind: "error_system", label: "Production-ready error handling system with UI components and repository mapping."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "focus_outline",
    label: "Keyboard focus visualization outline with theming support.",
    section: "Utilities",
    icon: Icons.crop,
    build: (context) => RegistryPlaceholder(kind: "focus_outline", label: "Keyboard focus visualization outline with theming support."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "image",
    label: "Placeholder entry preserving legacy image collection support.",
    section: "Utilities",
    icon: Icons.photo_library,
    build: (context) => RegistryPlaceholder(kind: "image", label: "Placeholder entry preserving legacy image collection support."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "locale_utils",
    label: "Date/time/duration unit helpers and file size formatting locales.",
    section: "Utilities",
    icon: Icons.language,
    build: (context) => RegistryPlaceholder(kind: "locale_utils", label: "Date/time/duration unit helpers and file size formatting locales."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "repeated_animation_builder",
    label: "Looping animation builder with interpolated values.",
    section: "Utilities",
    icon: Icons.loop,
    build: (context) => RegistryPlaceholder(kind: "repeated_animation_builder", label: "Looping animation builder with interpolated values."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "shadcn_localizations",
    label: "Full localization delegate and base translations.",
    section: "Utilities",
    icon: Icons.translate,
    build: (context) => RegistryPlaceholder(kind: "shadcn_localizations", label: "Full localization delegate and base translations."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "shadcn_localizations_en",
    label: "English translation bundle for ShadcnLocalizations.",
    section: "Utilities",
    icon: Icons.abc,
    build: (context) => RegistryPlaceholder(kind: "shadcn_localizations_en", label: "English translation bundle for ShadcnLocalizations."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "shadcn_localizations_extensions",
    label: "Formatting helpers for localized dates, times, durations, and picker labels.",
    section: "Utilities",
    icon: Icons.g_translate,
    build: (context) => RegistryPlaceholder(kind: "shadcn_localizations_extensions", label: "Formatting helpers for localized dates, times, durations, and picker labels."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "timeline_animation",
    label: "Keyframe-based animation timeline utilities.",
    section: "Utilities",
    icon: Icons.movie,
    build: (context) => RegistryPlaceholder(kind: "timeline_animation", label: "Keyframe-based animation timeline utilities."),
    canvasReady: false,
  ),
  RegistryEntry(
    kind: "wrapper",
    label: "Conditional wrapper for preserving widget structure.",
    section: "Utilities",
    icon: Icons.widgets,
    build: (context) => RegistryPlaceholder(kind: "wrapper", label: "Conditional wrapper for preserving widget structure."),
    canvasReady: false,
  ),
];
